#include "hal_data.h"

#include "zf_common_headfile.h"
#include "sdhi_sdcard/bsp_sdhi_sdcard.h"
/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    bsp_io_level_t readLevel = BSP_IO_LEVEL_LOW;
    fsp_err_t err;

    debug_init();

    ips200_init();
    SDcard_Init();
    SDCard_Operation();
    err = g_ioport.p_api->open(g_ioport.p_ctrl, g_ioport.p_cfg);
    assert(FSP_SUCCESS == err);
    ips200_full(RGB565_WHITE);
    ips200_clear();
              // ips200_show_string(10, 40, "Hello:");
               //ips200_show_chinese_string(70, 40, 16, "孔，凶，笨，鸽紧顿描绘", RGB565_BLUE);

               //ips200_show_string(10, 70, "");
               ips200_show_mixed_string(10, 30, 16,16, "沁园春·雪 北国风光，千里冰封，万里雪飘。望长城内外，惟余莽莽；大河上下，顿失滔滔。山舞银蛇，原驰蜡象，欲与天公试比高。须晴日，看红装素裹，分外妖娆。江山如此多娇，引无数英雄竞折腰。惜秦皇汉武，略输文采；唐宗宋祖，稍逊风骚。一代天骄，成吉思汗，只识弯弓射大雕。俱往矣，数风流人物，还看今朝。", RGB565_RED);

             //   ips200_show_int(40, 100, 1234, 4);
              //  ips200_show_string(40, 130, "hello world!");


            //ips200_show_mixed_string(10, 40, 16, 16, "在巅峰时期之后，她的个人生活开始更多进入公众视野，尤其是恋爱相关话题，让她从 内容创作者  逐渐变成  被围观的对象 ，围绕感情选择的争议，也让她一度陷入舆论压力，甚至出现过阶段性淡出，但重新回归后，她的风格明显更加多变，从甜系到御姐，再到各种尝试型造型，内容方向不再单一，也逐渐恢复了一定的讨论度，对不少老粉来说，这种 重新找回状态 的变化，某种程度上比单一人设更耐看。", RGB565_BLUE);
            //ips200_show_mixed_string(10, 80, 16, 16, "This is a test string with 中文 and 1234 numbers!", RGB565_RED);
    while(true)
    {
        R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);//
        
        g_ioport.p_api->pinRead(&g_ioport_ctrl, BSP_IO_PORT_01_PIN_10, &readLevel);
        g_ioport.p_api->pinWrite(&g_ioport_ctrl, BSP_IO_PORT_01_PIN_10, BSP_IO_LEVEL_HIGH - readLevel);
        

    }

}
